### ISSUE TITLE
Implement an entropy source that reads from a URL (f.e: https://www.random.org/cgi-bin/randbyte?nbytes={count}&format=f)

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#25]
Not too sure about this one: bytes extracted from random.org may be attacked (by eavesdropping or just because random.org may be unfair).

The problem is that, AFAIK, we don't have real sources of randomness in DART.

See http://wiki.openssl.org/index.php/Random_Numbers

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#25
