### ISSUE TITLE
Split impl.dart into client and server parts (was 'dart:io dependency in v0.5.0')

### ISSUE THREAD

**Issue by devoncarew** [izaera/cipher#41]
We're using this package in the context of a web app (actually a chrome app). The latest version has introduced a dependency on `dart:io`. We've temporarily pegged our version dependency at 0.4.0.

> packages/cipher/entropy/url_entropy_source.dart:9:8: Error: Library not found 'dart:io'.
>  import "dart:io";

Any chance this `dart:io` dependency could be removed, or only included from a `cipher_io.dart` entry-point?

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#41
