### ISSUE TITLE
Design a way to automatically load algorithm implementations

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#50]
The idea is to avoid the need to call initCipher() before using the library. I'll try to call initCipher() from Registry.create().

Also, it would be good to redesign initCipher() so that it can be tweaked to load only the algorithms used. This is a good starting point: http://blog.sethladd.com/2013/04/lazy-load-libraries-in-dart.html

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#50
