### ISSUE TITLE
Implement OAEP for RSA signature

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#59]
Need to check what we are actually implementing (I think it's textbook RSA) and decide if it needs to be changed or enhanced in the future.

More info about RSA standards here: http://www.drdobbs.com/rsa-digital-signatures/184404605
and here: https://en.wikipedia.org/wiki/PKCS_1

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#59
