### ISSUE TITLE
RSA key generator calls `new SecureRandom()` with no algorithm name

### ISSUE THREAD

**Issue by bshepherdson** [izaera/cipher#65]
If one calls `init()` on an `RSAKeyGenerator` without supplying a randomizer, it tries to call `new SecureRandom()`, which fails because it doesn't specify an algorithm name, and `""` is not a valid algorithm.

This can be worked around, of course, by supplying a randomizer oneself. But either the fallback should work, or the caller should be required to supply one.

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#65
