### ISSUE TITLE
Json Web Token : sha256 signature

### ISSUE THREAD

**Issue by amaurel** [izaera/cipher#71]
First I would like to thank you for your great work!

I need to generate Json web token (https://developers.google.com/accounts/docs/OAuth2ServiceAccount).
I'm currently using openssl to signed the token.
Here's the command line I am using.

```
openssl sha -sha256 -sign private.pem < data.txt
```

Is it possible to use cipher library to do the same thing ?
I could not find sha256 signer test case.

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#71
