### ISSUE TITLE
Spin off entropy to another project and make cipher independent of client/server

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#86]
I have entropy sources nearly finished but I have decided to spin off a new project for those who need entropy.

Currently entropy is complicating the code because it is implemented differently in client and server. And also, in server I have to differentiate between Windoze and Unixes. So I'm gonna remove it and move it to a different project. 

This will make cipher much easier to use and maintain as all code will be independent of client or server.

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#86
