### ISSUE TITLE
Make instantiation of algorithms standard and based on the algorithm name and a pseudo-DSL

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#87]
The idea is that a non-randomized algorithm state can be serialized/recovered with just its CipherParameters. I mean: if two algorithms with the same name receive the same CipherParameters, they must result in the same outputs for the same data.

Of course, this cannot be done if some algorithm is randomized, but in that case, the SecureRandom should be specified in the name so that it is made explicit. And also, it would still be considered the same algorithm, it's just that the randomization is different.

This change will allow to merge in pull request https://github.com/izaera/cipher/pull/82 that implements hashCode and equals for all CipherParameters. 

If I cannot express SecureRandom as algorithm names and I cannot get rid of ParametersWithRandom, I won't merge it in because I don't like to have unstable semantics for these methods.

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#87
