### ISSUE TITLE
When the input is long enough, SHA384 often returns wrong result. for short input like 10 20 bytes, it seems to be fine

### ISSUE THREAD

**Issue by izaera** [izaera/cipher#92]
Hi

in the dart cipher pub package
I found when the input is long enough, SHA384 often returns wrong result. for short input like 10 20 bytes, it seems to be fine.

btw, I'm testing in dartvm,

a test case:

SHA384Digest sha = new SHA384Digest();
print(sha.process(UTF8.encode('1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012')));

// output: [162, 16, 86, 170, 176, 212, 206, 236, 153, 72, 18, 214, 163, 232, 46, 58, 183, 219, 82, 127, 35, 105, 243, 234, 247, 111, 177, 42, 221, 159, 71, 14, 57, 121, 57, 192, 150, 98, 90, 70, 103, 148, 165, 98, 120, 84, 148, 243]
// and this is different from the result I get from any other framework:  8f3cbbf964af56b83b52f7182cd171fab20810103603d4213217914145388dca1cad5fe88dcdbc56cf3ff5fc7fb82ae8

**Comment by stevenroose** [comment]
This issue was moved to PointyCastle/pointycastle#92
