### ISSUE TITLE
SHA-256/ECDSA signer gives invalid results with some inputs

### ISSUE THREAD

**Issue by mpcomplete** [izaera/cipher#95]
I'm using cipher in a project, and I have a simple fuzz tester to verify my sign+verify code is correct. Occasionally it will fail with certain seeds to the SecureRandom number generator. Here is a sample reduced test case that fails. (You can add this code to cipher/test/signers/ecdsa_signer_test.dart to see it fail in cipher's test suite).

import 'dart:typed_data';
import "package:unittest/unittest.dart";
void fail()
{
  // Bad seed:
  List<int> key = [ 67, 3, 241, 75, 143, 78, 115, 99, 21, 242, 180, 43, 26, 7, 194, 20 ];
  List<int> iv = [ 87, 117, 137, 182, 2, 199, 132, 230, 120, 12, 109, 177, 34, 197, 186, 206 ];
  KeyParameter keyParam = new KeyParameter(new Uint8List.fromList(key));
  ParametersWithIV paramsIV = new ParametersWithIV(keyParam, new Uint8List.fromList(iv));
  SecureRandom random = new SecureRandom('AES/CTR/AUTO-SEED-PRNG')
      ..seed(paramsIV);

  // Bad test pattern:
  final Uint8List kTestBytes = new Uint8List.fromList(<int>[1, 2, 3]);

  // Bad key pair:
  final ECDomainParameters ecDomain = new ECDomainParameters('prime256v1');
  ECPrivateKey privateKey = new ECPrivateKey(
      new BigInteger("49796319969581709255674594372216982488391390668014565621687620773258125227296"),
      ecDomain);
  ECPoint Q = privateKey.parameters.G \* privateKey.d;
  ECPublicKey publicKey = new ECPublicKey(Q, privateKey.parameters);

  Signer signer = new Signer('SHA-256/ECDSA');
  PrivateKeyParameter signParams = new PrivateKeyParameter(privateKey);
  signer.init(true, new ParametersWithRandom(signParams, random));
  ECSignature signature = signer.generateSignature(kTestBytes);

  signer.init(false, new PublicKeyParameter(publicKey));
  bool verify = signer.verifySignature(kTestBytes, signature);
  expect(verify, true);
}

**Comment by izaera** [comment]
Hi:

The project has been moved to a new place where some more people are collaborating on it: https://github.com/PointyCastle/pointycastle <https://github.com/PointyCastle/pointycastle>

Please consider using the new version as I’m no longer maintaining cipher. Sorry for the inconvenience. Nevertheless, I will place a notice in the home page of the project so that it does not happen again.

Cheers,
Ivan
