### ISSUE TITLE
Fix SHA-512 hash for use with Flutter.

### ISSUE THREAD

**Issue by gurmukhp** [izaera/cipher#97]
Hey there!

I'm building an app in  Flutter and need to generate a SHA-512 hash. Unfortunately I'm unable to use PointyCastle in Flutter due to the dependency on dart:mirror. 

I was able to go through the PointyCastle bug fixes and [found](https://github.com/PointyCastle/pointycastle/commit/22665686fe62b7dd086287982d6cf63dfc198678) the change required to fix the SHA-512. 

Please would you consider adding this update? Currently there is no known way to use SHA-512 in Flutter using Dart.

**Comment by izaera** [comment]
@gurmukhp Mmm... I understand your reasons but I'm not sure that fixing this project is the best option, as it is not maintained any more 🤔.

Doing that will mean that you won't get any updates contributed to PointyCastle, which may lead to vulnerabilities in your project. In short, it would be equivalent to forking this project and maintaining it yourself (which I still don't recommend).

The best thing IMO would be adapting PointyCastle to not using `dart:mirrors` if that is necessary. In the meantime you could use your own version of this project (a fork or a locally modified version, for instance).

On the other hand, if it is impossible for PointyCastle to avoid using `dart:mirrors` you are still stuck with the same problem: that you would be using an unmaintained/self maintained project...

Why does PointyCastle use `dart:mirrors`? Is it unavoidable?

**Comment by gurmukhp** [comment]
Thanks for the quick response!

To be honest, I only started writing Dart a few weeks ago, so am not too sure as to why PointyCastle still uses `dart:mirrors`. I've seen that the Flutter team are persistent in not supporting mirrors for good reason. It looks like the PointyCastle team have an open bug to remove the dependency but I'm not sure if it's actively being worked on.

I've raised a bug on the PointyCastle repo addressing this. 

I like the idea of keeping a local copy of the changes, do you know how I could reference my `pubspec.yaml` file to reference my fork?

Totally understand it's not secure, I'm playing around with building apps so not sure this'll ever go into production.

thanks again!

**Comment by izaera** [comment]
Ah, OK. In that case, the best option would be the modified local copy :-).

Regarding the `pubspec.yaml` I stopped using Dart long ago, so I'm afraid I cannot help you, but I suppose it shouldn't be difficult at all, as nearly every package manager out there has that option.

**Comment by izaera** [comment]
https://www.dartlang.org/tools/pub/dependencies

Maybe using a `file://` type URL and `hosted` could make it?

**Comment by gurmukhp** [comment]
Thanks for this! I'll take a look. Appreciate your help.
